### ISSUE TITLE
Arma Reforger Overthrow bug

### ISSUE THREAD

**Issue by cretugabriel98** [ArmaOverthrow/Overthrow.Arma4#2]
Overthrow bug

Can't compile "Game" script module

Scripts/Game/GameMode/OVT_OverthrowGameMode.c(122):
Overloading event 'OnPlayerDisconnected' is not allowed
![image](https://user-images.githubusercontent.com/122006922/210727232-41175a1f-b62a-45c0-a10a-01e49a2607a6.png)

**Comment by moggesmith10** [comment]
This latest update seems to have solved this.
