### ISSUE TITLE
[Possible Bug] [SP] Owned vehicle is deleted

### ISSUE THREAD

**Issue by ColonelX11** [ArmaOverthrow/Overthrow.Arma4#43]
I have noticed that the car given to the player at the beginning disappears shortly after leaving it somewhere, although I left it locked and undamaged. I was able to reproduce this issue several times by leaving it somewhere and going to another town. The items in the vehicle's cargo would disappear too.

I am not 100% sure whether this is intentional or if there is some place where vehicles are supposed to be stored, which is why I have labeled this as a possible bug.

**Comment by z3r0d4h3r0** [comment]
Same here, on a dedicated server.
The vehicule was stored in the garage of my starting house.

Here it's the save file of the vehicule.

`{
    "m_sId": "6629a622-0000-009d-0001-5bbfb78020a8",
    "m_iLastSaved": 1714014369,
    "m_rPrefab": "D9B91FAB817A6033",
    "m_pTransformation": {
        "m_vOrigin": [
            7703.98925,
            12.99868,
            8107.83593
        ],
        "m_vAngles": [
            40.85709,
            -1.34631,
            -0.0021
        ]
    },
    "m_aComponents": [
        {
            "_type": "PlayerOwnerData",
            "m_pData": {
                "m_iDataLayoutVersion": 1,
                "m_sOwnerUID": "",
                "m_bIsLocked": false
            }
        },
        {
            "_type": "InventoryStorageComponent",
            "m_pData": {
                "m_iDataLayoutVersion": 1,
                "m_iPriority": 0,
                "m_ePurposeFlags": 1,
                "m_aSlots": [
                    {
                        "m_iSlotIndex": 0,
                        "_type": "Item",
                        "m_pEntity": {
                            "m_sId": "6629a622-0000-009e-0001-23c64780fca4",
                            "m_iLastSaved": 1714014369,
                            "m_rPrefab": "C3F1FA1E2EC2B345"
                        }
                    },
                    {
                        "m_iSlotIndex": 1,
                        "_type": "Item",
                        "m_pEntity": {
                            "m_sId": "6629a622-0000-009f-0001-76b9ed80c2a8",
                            "m_iLastSaved": 1714014369,
                            "m_rPrefab": "C3F1FA1E2EC2B345"
                        }
                    },
                    {
                        "m_iSlotIndex": 2,
                        "_type": "Item",
                        "m_pEntity": {
                            "m_sId": "6629a622-0000-00a0-0001-223e44805178",
                            "m_iLastSaved": 1714014369,
                            "m_rPrefab": "12D5AD21E383B768"
                        }
                    },
                    {
                        "m_iSlotIndex": 3,
                        "_type": "Item",
                        "m_pEntity": {
                            "m_sId": "6629a622-0000-00a1-0001-173f2e80d95e",
                            "m_iLastSaved": 1714014369,
                            "m_rPrefab": "33B2DFDCD0EBA3DB"
                        }
                    }
                ]
            }
        }
    ]
}`

**Comment by AndyClausen** [comment]
Same, both on player-hosted and dedi

**Comment by KingRayVet** [comment]
I don't know whether I should enter a stand-alone issue for this, but often I save my entire ArmaReforger folder on another drive. I copied everything over to the game's drive and when I started the game, my vehicle was gone. I have a mod to keep it put. This is the first time that has happened since I started playing Overthrow. What a disaster in which I'll have to start over again or run around without a vehicle until I can afford to buy another one. There were items in that off-road vehicle. 

Should I make this a separate issue? 

Player Data:

[PlayerData.3959c62f-b958-4cdc-89f2-ecb4f7141986.json](https://github.com/ArmaOverthrow/Overthrow.Arma4/files/15125977/PlayerData.3959c62f-b958-4cdc-89f2-ecb4f7141986.json)

Vehicle file:

[66192754-0000-1660-0001-48139000b874.json](https://github.com/ArmaOverthrow/Overthrow.Arma4/files/15125985/66192754-0000-1660-0001-48139000b874.json)

**Comment by AndyClausen** [comment]
Which mod did you use to keep the vehicle spawned in?

**Comment by KingRayVet** [comment]
Keep Abandoned Vehicles by Kexanone

**Comment by KingRayVet** [comment]
> Which mod did you use to keep the vehicle spawned in?

Sorry, I responded via email and it doesn't end up over here. I use **_Keep Abandoned Vehicles by Kexanone_**.

**Comment by KingRayVet** [comment]
BTW, this only happens if I save the game when the soldier is outside of the vehicle. If he's inside, the game restores with him in the vehicle. Thought that was something important to say.
