### ISSUE TITLE
Warehouses

### ISSUE THREAD

**Issue by aaronstatic** [ArmaOverthrow/Overthrow.Arma4#5]
Warehouses will work basically the same as they do in Overthrow Community Edition, with a few changes

### Players
- Players can build a warehouse in a town controlled by the RF, or at RF bases
- Players can buy any existing warehouses in any town, regardless of control
- Warehouses will be globally accessible by anyone in the RF by default, or the owning player can choose to make one private and control access

### Linking
- Warehouses will not be linked by default
- Warehouses can be linked by RF officers for an ongoing fee per warehouse, but not if they are set as private by the owner. Funds for this link will be taken from Resistance Funds, and the link will be broken if there is not enough money to pay that bill
- Private warehouses can never be linked, and changing a warehouse to private will break that link and remove the ongoing payment from the RF
- RF officers can unlink a warehouse at any time

### Difficulty
- A difficulty option will allow all public warehouses to be linked for no fee. The "Easy" difficulty preset will have this turned on by default, all other difficulties will have it turned off

### Other features
- Warehouses will be able to store a limited number of road vehicles, but they will not be linked
- Warehouses (both private and public, linked and not linked) will be high priority targets for OF special forces. They will attempt to remove items stored at that particular warehouse (not the linked items) and may also try to destroy that warehouse and the items or vehicles in it (again, not the linked items)

**Comment by Iceclaws192** [comment]
is this still open for development
cause Ill take a look into it
