### ISSUE TITLE
[Bug][RHS] Soldier equipment respawn issue

### ISSUE THREAD

**Issue by ColonelX11** [ArmaOverthrow/Overthrow.Arma4#50]
I wasn't sure where to post this since it is a mod-related issue, so I put it in the main issue thread. Please apologize if this isn't the right place.

I have noticed that when using the RHS modification in combination with the compatibility addon for your scenario, AFRF soldiers would (sometimes?) be replaced with Soviet Forces equipped with vanilla clothing. For example, I attacked a radio tower and killed two AFRF soldiers, only to find out they would be reinforced by their "comrades from another generation". I have not yet been able to investigate this issue any further.

The rest seems to be working fine since your last update. Thank you for your amazing work!

**Comment by CowboyPilotUSA** [comment]
This might be a missed configuration in the RHS Compatibility when it comes to the faction select of various unit types. I recalled seeing this issue, and I think it was with Grenadier unit.

**Comment by armazac** [comment]
Should be fixed now in RHS Compatibility 1.0.7
