### ISSUE TITLE
Cycle waypoints don't work

### ISSUE THREAD

**Issue by rekterakathom** [ArmaOverthrow/Overthrow.Arma4#61]
Cycle waypoints don't seem to make the waypoints repeat, like they are supposed to. Logs are full of 'NULL waypoint' warnings.

I am currently looking into this, but I haven't been able to come up with anything. Changing the prefab for the cycle waypoint does something (no more null errors..,?) but the units still refuse to actually cycle the waypoints. I don't think the cycle waypoint is bugged in the game itself, I've confirmed that it works for at least one person so I believe it's something in OVT.

**Comment by armazac** [comment]
This should be fixed now in v1.2.41
