### ISSUE TITLE
No pistol in the start

### ISSUE THREAD

**Issue by rekterakathom** [ArmaOverthrow/Overthrow.Arma4#69]
## Version information
- Platform: PC
- Game version: 1.2
- Overthrow version: 1.2.38

## Describe the problem
The starting pistol is missing

## To Reproduce
Steps to reproduce the problem:
1. Start a new game
2. Observe missing pistol

## Expected behavior
Pistol in pants

## Where did the issue occur?
Singleplayer

## Additional context
I had a pistol when starting for the first time ever, when the tutorial popped up. Ever since new starts have not given me a pistol to start with.

## Attach logs from the session the problem occurred in
[console.log](https://github.com/user-attachments/files/16042249/console.log)

Where to find logs:
- Windows - `Documents\my games\ArmaReforger\logs`

**Comment by armazac** [comment]
Fixed in v1.2.40
