### ISSUE TITLE
Increased stealth at night

### ISSUE THREAD

**Issue by aaronstatic** [ArmaOverthrow/Overthrow.Arma4#9]
The range you can be seen from should be reduced at night time, maybe even react to the ambient light level or be reduced in shadows if possible

**Comment by KingOfCarter** [comment]
The stealth attribution in the new engine is insane! I am blown away with the capabilities of all the settings available to fine tune every aspect of perception. You opened up my eyes when I needed to make some edits for my personal mission on Overthrow reforged
